### ISSUE TITLE
Provide API to extract/poll bill details for each project from a billing account

### ISSUE THREAD

**Issue by ceecer1** [googleapis/python-billing#224]
This feature would be great and hopefully most orgs would require it. This feature enables customers to do the projection of bill details to anywhere they want.

**Comment by TLazarevic** [comment]
+ 1

**Comment by parthea** [comment]
Thanks for opening this feature request. I'm going to close this issue as a duplicate of https://issuetracker.google.com/issues/70525274 which is in the [public issue tracker](https://cloud.google.com/support/docs/issue-trackers) for the [Billing API](https://issuetracker.google.com/savedsearches/559770).
